INSERT INTO municipio VALUES (0,6,'Kansas City');
INSERT INTO municipio VALUES (1,9,'Paducah');
INSERT INTO municipio VALUES (2,9,'Richland');
INSERT INTO municipio VALUES (3,12,'Hattiesburg');
INSERT INTO municipio VALUES (4,15,'Green River');
INSERT INTO municipio VALUES (5,8,'Rock Springs');
INSERT INTO municipio VALUES (6,4,'Forrest City');
INSERT INTO municipio VALUES (7,2,'Lodi');
INSERT INTO municipio VALUES (8,17,'Hilo');
INSERT INTO municipio VALUES (9,6,'Joplin');
INSERT INTO municipio VALUES (10,0,'Columbus');
INSERT INTO municipio VALUES (11,10,'Caguas');
INSERT INTO municipio VALUES (12,7,'Des Moines');
INSERT INTO municipio VALUES (13,2,'Virginia Beach');
INSERT INTO municipio VALUES (14,3,'Grand Island');
INSERT INTO municipio VALUES (15,18,'Douglas');
INSERT INTO municipio VALUES (16,5,'Johnson City');
INSERT INTO municipio VALUES (17,16,'Fountain Valley');
INSERT INTO municipio VALUES (18,6,'Garland');
INSERT INTO municipio VALUES (19,19,'Colorado Springs');
INSERT INTO municipio VALUES (20,2,'Reno');
INSERT INTO municipio VALUES (21,4,'Montgomery');
INSERT INTO municipio VALUES (22,6,'Rancho Cucamonga');
INSERT INTO municipio VALUES (23,9,'Milford');
INSERT INTO municipio VALUES (24,0,'Pascagoula');
INSERT INTO municipio VALUES (25,18,'Fullerton');
INSERT INTO municipio VALUES (26,5,'Loudon');
INSERT INTO municipio VALUES (27,5,'Murrieta');
INSERT INTO municipio VALUES (28,13,'Baton Rouge');
INSERT INTO municipio VALUES (29,8,'Rhinelander');
INSERT INTO municipio VALUES (30,4,'Hammond');
INSERT INTO municipio VALUES (31,17,'Melrose');
INSERT INTO municipio VALUES (32,16,'Rock Springs');
INSERT INTO municipio VALUES (33,1,'Memphis');
INSERT INTO municipio VALUES (34,9,'Charleston');
INSERT INTO municipio VALUES (35,17,'Sugar Land');
INSERT INTO municipio VALUES (36,16,'Rock Springs');
INSERT INTO municipio VALUES (37,1,'Delta Junction');
INSERT INTO municipio VALUES (38,0,'Charlotte');
INSERT INTO municipio VALUES (39,1,'North Little Rock');
INSERT INTO municipio VALUES (40,3,'Norwalk');
INSERT INTO municipio VALUES (41,12,'Midwest City');
INSERT INTO municipio VALUES (42,4,'College Park');
INSERT INTO municipio VALUES (43,19,'Egg Harbor');
INSERT INTO municipio VALUES (44,6,'Troy');
INSERT INTO municipio VALUES (45,9,'Sedalia');
INSERT INTO municipio VALUES (46,14,'Fulton');
INSERT INTO municipio VALUES (47,6,'Hayward');
INSERT INTO municipio VALUES (48,9,'Olean');
INSERT INTO municipio VALUES (49,14,'Pierre');
