INSERT IGNORE INTO departamento VALUES (0,'Port Washington','Wyoming');
INSERT IGNORE INTO departamento VALUES (1,'Fremont','Illinois');
INSERT IGNORE INTO departamento VALUES (2,'Altoona','Illinois');
INSERT IGNORE INTO departamento VALUES (3,'New London','Louisiana');
INSERT IGNORE INTO departamento VALUES (4,'Salem','Rhode Island');
INSERT IGNORE INTO departamento VALUES (5,'Corvallis','North Dakota');
INSERT IGNORE INTO departamento VALUES (6,'Miami Beach','Massachusetts');
INSERT IGNORE INTO departamento VALUES (7,'Everett','Nevada');
INSERT IGNORE INTO departamento VALUES (8,'Hartford','Idaho');
INSERT IGNORE INTO departamento VALUES (9,'Mount Pleasant','Nevada');
INSERT IGNORE INTO departamento VALUES (10,'Austin','Michigan');
INSERT IGNORE INTO departamento VALUES (11,'Albuquerque','New Mexico');
INSERT IGNORE INTO departamento VALUES (12,'Brunswick','South Dakota');
INSERT IGNORE INTO departamento VALUES (13,'Yigo','West Virginia');
INSERT IGNORE INTO departamento VALUES (14,'Midwest City','Missouri');
INSERT IGNORE INTO departamento VALUES (15,'Bowling Green','Wyoming');
INSERT IGNORE INTO departamento VALUES (16,'Burbank','Idaho');
INSERT IGNORE INTO departamento VALUES (17,'Plattsburgh','New York');
INSERT IGNORE INTO departamento VALUES (18,'Fremont','Virginia');
INSERT IGNORE INTO departamento VALUES (19,'Burlingame','West Virginia');
